### ISSUE TITLE
That Split is Wrong

### ISSUE THREAD

**Issue by dragos-rosca** [osstotalsoft/generator-graphql-rocket#1]
https://github.com/osstotalsoft/generator-graphql-rocket/blob/fac0f3f93c42c02be20863edf3caca94fb042aa4/generators/app/templates/infrastructure/src/db/multiTenancy/tenantFilters.js#L29

If I split by " as " I expect the table name to be the first item in the array.
The code should be:
```javascript
const tableName = tableNameComponents[0];
```

**Comment by dragos-rosca** [comment]
Also when we have a different schema then "dbo" this will crash later when we search the table name in the tenant agnostic table list.
We need a more robust system of identifying where to put that "where TenantId = @p0" filter.
PS: Someone might put table full name, like: catalog.schema.tableName ...

**Comment by oncicaradupopovici** [comment]
The tenancy filter will be power by npm package @totalsoft/knex-filters, see https://github.com/osstotalsoft/nodebb/pull/9
