### ISSUE TITLE
Question: Why is the messaging feature conditioned by the subscription feature?

### ISSUE THREAD

**Issue by oncicaradupopovici** [osstotalsoft/generator-graphql-rocket#15]
This is more of a question....
Why is the messaging feature conditioned by the subscription feature? 
One might want to receive some notifications via messaging and update some internal state, like read models.... no gql subscriptions required

**Comment by alexandra-c** [comment]
This is a good question. Usually, the messaging feature and subscriptions were used together, or at least that was the need in our current projects, but you have a point. Maybe someone wants to use  messaging and not subscriptions. I will probably remove  this limitation. Thank you for your feedback! 😊
