### ISSUE TITLE
Outer Join

### ISSUE THREAD

**Issue by dragos-rosca** [osstotalsoft/generator-graphql-rocket#25]
https://github.com/osstotalsoft/generator-graphql-rocket/blob/e66180e2947eb73cdbbd793589f685f86bfe0f45/generators/app/templates/infrastructure/src/db/multiTenancy/tenancyFilter.js#L18

Found a new oversite on /src/db/multiTenancy/tenancyFilter.js .
If I build a query with any kind of `outer join` the library will automatically add a `where TenantId` clause. But the purpose of `outer join` is to show data from a table even if the joined table returns `null`. If the join table shows `null` on all columns that means `t.TenantId` will also be `null` and our forced where clause will remove the row.

There is a quick fix that might work, to just put `where [...] and (tenantId is null or tenantId='value') [...]`. Or we can go with a more sophisticated fix that will notice the `outer joins` and put the tenant restriction in the `on` space like: `[...] from A left join B on A.id = B.idOfA and B.tenantId = 'value' [...]` this will bring in the correct data. But you have left, right and full outer join and all cases must be covered.

**Comment by oncicaradupopovici** [comment]
Added a new definition for tenancy filter:
const filter = createFilter(tableHasColumnTenantId, {
    onSelect: {
      from: addWhereTenantIdClause,
      innerJoin: addWhereTenantIdClause,
      leftJoin: addOnTenantIdClause,
    },
    onUpdate: addWhereTenantIdClause,
    onDelete: addWhereTenantIdClause,
    onInsert: (_table, _alias, _queryBuilder, inserted) => {
      inserted[columnTenantId] = tenantId
    },
  })
